language: python
python:
  - "2.6"
  - "2.7"
#  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# command to run tests
script:
  - flake8 .
#  - "nosetests -v test/"
#  - mkdir -p doc/_build/html -v
#  - sphinx-build -v doc doc/_build/html
#  - rm -rf doc/_build/html -v
notifications:
  irc:
    channels:
      - "irc.esper.net#Ultros-travis"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"